<?xml version="1.0" encoding="UTF-8"?>
<pages xmlns="http://jboss.org/schema/seam/pages" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://jboss.org/schema/seam/pages http://jboss.org/schema/seam/pages-2.3.xsd"
	no-conversation-view-id="/login.xhtml" login-view-id="/login.xhtml">

	<page view-id="*">
		<navigation>

			<rule if-outcome="home">
				<redirect view-id="/home.xhtml" />
			</rule>
			
			<rule if-outcome="login">
			    <end-conversation before-redirect="true" root="true" />
				<redirect view-id="/login.xhtml" />
			</rule>
			
		</navigation>
	</page>

	<!-- Controle de Autenticação -->

	<page login-required="true" view-id="/pages/*" />
	<page login-required="true" view-id="/resources/*" />
	<page login-required="true" view-id="/layout/*" />
	<page login-required="true" view-id="/componentes/*" />

	<exception class="org.jboss.seam.framework.EntityNotFoundException" log-level="info">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Registro não encontrado</message>
		</redirect>
	</exception>

	<exception class="org.hibernate.StaleObjectStateException" log-level="info">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Esse registro acabou de ser alterado por outra transação, por favor tente novamente!</message>
		</redirect>
	</exception>

	<!-- Não mostra tela de Blocker -->
	<exception class="org.hibernate.QueryException" log-level="info"> 
		<redirect view-id="/error.xhtml"> 
			<message severity="error">Problemas para realizar a consulta do Banco de Dados!</message> 
		</redirect> 
	</exception> 

	<exception class="org.hibernate.exception.SQLGrammarException" log-level="info"> 
		<redirect view-id="/error.xhtml"> 
			<message severity="error">Problemas para realizar a consulta do Banco de Dados!</message> 
		</redirect> 
	</exception> 

	<exception class="org.hibernate.exception.ConstraintViolationException" log-level="info">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Registro duplicado!</message>
		</redirect>
	</exception>

	<exception class="org.postgresql.util.PSQLException" log-level="info">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Registro duplicado!</message>
		</redirect>
	</exception>

	<exception class="javax.persistence.EntityNotFoundException" log-level="info">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Registro não existe no banco de dados!</message>
		</redirect>
	</exception>

	<exception class="javax.persistence.EntityExistsException" log-level="info">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Registro duplicado!</message>
		</redirect>
	</exception>

	<exception class="javax.persistence.OptimisticLockException" log-level="info">
		<end-conversation />
		<redirect view-id="/error.xhtml">
			<message severity="warn">Esse registro acabou de ser alterado por outra transação, por favor tente novamente!</message>
		</redirect>
	</exception>

	<exception class="org.jboss.seam.security.AuthorizationException" log-level="info" log="false">
		<redirect view-id="/error.xhtml">
			<message severity="error">Você não tem autorização para acessar essa página!</message>
		</redirect>
	</exception>

	<exception class="org.jboss.seam.security.NotLoggedInException" log-level="error">
		<redirect view-id="/login.xhtml">
			<message severity="error">#{messages['org.jboss.seam.NotLoggedIn']}</message>
		</redirect>
	</exception>

	<exception class="javax.faces.application.ViewExpiredException" log-level="info" log="false">
		<redirect view-id="/login.xhtml">
			<message severity="warn">Sua sessão expirou, por favor, tente novamente</message>
		</redirect>
	</exception>

	<exception class="java.lang.NullPointerException" log-level="info">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Erro inesperado, por favor tente novamente</message>
		</redirect>
	</exception>

	<exception class="java.lang.NumberFormatException" log-level="info">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Formato do valor invalido</message>
		</redirect>
	</exception>

	<exception class="java.lang.SecurityException" log-level="info">
		<redirect view-id="/login.xhtml">
			<message severity="warn">Violação de segurança</message>
		</redirect>
	</exception>

	<exception class="java.lang.NoClassDefFoundError" log-level="info">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Erro inesperado, por favor tente novamente</message>
		</redirect>
	</exception>

	<exception class="javax.faces.webapp.FacesServlet" log-level="info">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Erro inesperado, por favor tente novamente</message>
		</redirect>
	</exception>

	<exception class="java.lang.ArithmeticException" log-level="info">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Problemas ao efetuar o calculo</message>
		</redirect>
	</exception>

	<exception class="java.lang.ArrayIndexOutOfBoundsException" log-level="info">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Não encontramos o indice solicitado na lista</message>
		</redirect>
	</exception>

	<exception class="java.lang.ClassCastException" log-level="info">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Erro inesperado, por favor tente novamente</message>
		</redirect>
	</exception>

	<exception class="javax.persistence.PersistenceException" log-level="info">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Erro inesperado, por favor tente novamente</message>
		</redirect>
	</exception>

	<exception class="java.lang.ClassNotFoundException" log-level="info">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Erro inesperado, por favor tente novamente</message>
		</redirect>
	</exception>

	<exception class="java.lang.IllegalAccessException" log-level="info">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Erro inesperado, por favor tente novamente</message>
		</redirect>
	</exception>

	<exception class="java.lang.IllegalArgumentException" log-level="info">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Erro inesperado, por favor tente novamente</message>
		</redirect>
	</exception>

	<exception class="java.lang.IndexOutOfBoundsException" log-level="info">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Erro inesperado, por favor tente novamente</message>
		</redirect>
	</exception>

	<exception class="javax.faces.view.facelets.TagAttributeException" log-level="info">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Estamos com problema nesta pagina, por favor tente novamente mais tarde.</message>
		</redirect>
	</exception>

	<exception class="javax.el.PropertyNotFoundException" log-level="info">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Estamos com problema nesta pagina, por favor tente novamente mais tarde.</message>
		</redirect>
	</exception>

	<exception class="javax.faces.view.facelets.FaceletException" log-level="info">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Estamos com problema nesta pagina, por favor tente novamente mais tarde.</message>
		</redirect>
	</exception>

	<exception class="org.jboss.el.parser.ParseException" log-level="info">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Estamos com problema nesta pagina, por favor tente novamente mais tarde.</message>
		</redirect>
	</exception>

	<exception class="javax.servlet.ServletException" log-level="info">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Estamos com problema nesta pagina, por favor tente novamente mais tarde.</message>
		</redirect>
	</exception>

	<exception class="java.io.FileNotFoundException" log-level="info">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Não encontramos o arquivo desejado.</message>
		</redirect>
	</exception>

	<exception class="java.lang.IllegalStateException" log-level="info">
		<redirect view-id="/error.xhtml">
			<message severity="warn">Estamos com problema nesta pagina, por favor tente novamente mais tarde.</message>
		</redirect>
	</exception>

	<exception class="org.jboss.seam.ConcurrentRequestTimeoutException" log-level="trace">
		<http-error error-code="503" />
	</exception>

	<exception>
		<redirect view-id="/error.xhtml">
			<message severity="error">Erro inesperado, por favor tente novamente</message>
		</redirect>
	</exception>
</pages>
